/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaagenciaviagens.novoview;

import java.util.ArrayList;
import sistemaagenciaviagens.dao.BancoDeDados;
import sistemaagenciaviagens.model.ClienteModel;
import sistemaagenciaviagens.model.FuncionarioModel;
import sistemaagenciaviagens.model.HotelModel;
import sistemaagenciaviagens.model.LocalModel;
import sistemaagenciaviagens.model.PlanoModel;
import sistemaagenciaviagens.model.TransporteModel;
import sistemaagenciaviagens.uteis.ManipulaDB;

/**
 *
 * @author Caio
 */
public class SistemaAgenciaViagensView2 extends javax.swing.JFrame {

    /**
     * Creates new form SistemaAgenciaViagensView
     */
    public SistemaAgenciaViagensView2() {
        recuperarTabelas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        localButton = new javax.swing.JButton();
        funcionarioButton = new javax.swing.JButton();
        hotelButton = new javax.swing.JButton();
        transporteButton = new javax.swing.JButton();
        planoDeViagemButton = new javax.swing.JButton();
        clienteButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        localButton.setText("Local");
        localButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localButtonActionPerformed(evt);
            }
        });

        funcionarioButton.setText("Funcionario");
        funcionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioButtonActionPerformed(evt);
            }
        });

        hotelButton.setText("Hotel");
        hotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelButtonActionPerformed(evt);
            }
        });

        transporteButton.setText("Transporte");
        transporteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transporteButtonActionPerformed(evt);
            }
        });

        planoDeViagemButton.setText("Plano de Viagem");
        planoDeViagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planoDeViagemButtonActionPerformed(evt);
            }
        });

        clienteButton.setText("Cliente");
        clienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(funcionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transporteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(planoDeViagemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(sairButton, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcionarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transporteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planoDeViagemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        
        salvarTabelas();
        System.exit(0);
        
        
    }//GEN-LAST:event_sairButtonActionPerformed

    private void funcionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioButtonActionPerformed
        
        FuncionarioView fun = new FuncionarioView();
        fun.setVisible(true);
        
    }//GEN-LAST:event_funcionarioButtonActionPerformed

    private void localButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localButtonActionPerformed
        
        LocalView lcl = new LocalView();
        lcl.setVisible(true);
        
    }//GEN-LAST:event_localButtonActionPerformed

    private void hotelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelButtonActionPerformed
        
        HotelView htl = new HotelView();
        htl.setVisible(true);
        
    }//GEN-LAST:event_hotelButtonActionPerformed

    private void transporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transporteButtonActionPerformed
        
        TransporteView trp = new TransporteView();
        trp.setVisible(true);
        
    }//GEN-LAST:event_transporteButtonActionPerformed

    private void planoDeViagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planoDeViagemButtonActionPerformed
        
        PlanoView pln = new PlanoView();
        pln.setVisible(true);
        
    }//GEN-LAST:event_planoDeViagemButtonActionPerformed

    private void clienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteButtonActionPerformed
        
        ClienteView cli = new ClienteView();
        cli.setVisible(true);
        
    }//GEN-LAST:event_clienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAgenciaViagensView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAgenciaViagensView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAgenciaViagensView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAgenciaViagensView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaAgenciaViagensView2().setVisible(true);
            }
        });
    }
    
    
    public static void salvarTabelas(){
        ArrayList<Object> tabelaLcl = new ArrayList<>();
        ArrayList<Object> tabelaF = new ArrayList<>();
        ArrayList<Object> tabelaCli = new ArrayList<>();
        ArrayList<Object> tabelaHtl = new ArrayList<>();
        ArrayList<Object> tabelaTpt = new ArrayList<>();
        ArrayList<Object> tabelaPln = new ArrayList<>();
        
        for(Object local : BancoDeDados.getTabelaLocal()){
            tabelaLcl.add(local);
        }
        
        for (Object funcionario : BancoDeDados.getTabelaFuncionario()) {
            tabelaF.add(funcionario);
        }
        
        for (Object cliente : BancoDeDados.getTabelaCliente()) {
            tabelaCli.add(cliente);
        }
        
        for (Object hotel : BancoDeDados.getHotelTable()) {
            tabelaHtl.add(hotel);
        }
        
        for (Object transporte : BancoDeDados.getTransporteTable()) {
            tabelaTpt.add(transporte);
        }
        
        for (Object plano : BancoDeDados.getPlanoTable()) {
            tabelaPln.add(plano);
        }
        
        try {
            ManipulaDB.salvarArquivo(tabelaLcl, "banco/local.dat");
            
            ManipulaDB.salvarArquivo(tabelaF, "banco/funcionario.dat");
            
            ManipulaDB.salvarArquivo(tabelaCli, "banco/cliente.dat");
            
            ManipulaDB.salvarArquivo(tabelaHtl, "banco/hotel.dat");
            
            ManipulaDB.salvarArquivo(tabelaTpt, "banco/transporte.dat");
            
            ManipulaDB.salvarArquivo(tabelaPln, "banco/plano.dat");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }
    
    public static void recuperarTabelas(){
        System.out.println("Conectando ao Banco de Dados");
        
        try {
            ArrayList tabelaL = ManipulaDB.recuperarArquivo("banco/local.dat");
            ArrayList tabelaF = ManipulaDB.recuperarArquivo("banco/funcionario.dat");
            ArrayList tabelaC = ManipulaDB.recuperarArquivo("banco/cliente.dat");
            ArrayList tabelaH = ManipulaDB.recuperarArquivo("banco/hotel.dat");
            ArrayList tabelaT = ManipulaDB.recuperarArquivo("banco/transporte.dat");
            ArrayList tabelaP = ManipulaDB.recuperarArquivo("banco/plano.dat");
            
            // Local
            
            if(tabelaL != null){
                ArrayList<LocalModel> tLocal = new ArrayList<LocalModel>();
                
                for (Object o : tabelaL) {
                    LocalModel lcl = (LocalModel) o;
                    
                    tLocal.add(lcl);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tLocal.size()) > 0){
                    BancoDeDados.setProximoCodigoLocal(tLocal.get(tLocal.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoLocal(BancoDeDados.getProximoCodigoLocal());
                }
                
                BancoDeDados.setTabelaLocal(tLocal);
            }
            
            // Funcionario
            
            if(tabelaF != null){
                ArrayList<FuncionarioModel> tFuncionario = new ArrayList<FuncionarioModel>();
                
                for (Object o : tabelaF) {
                    FuncionarioModel f = (FuncionarioModel) o;
                    
                    tFuncionario.add(f);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tFuncionario.size()) > 0){
                    BancoDeDados.setProximoCodigoFuncionario(tFuncionario.get(tFuncionario.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoFuncionario(BancoDeDados.getProximoCodigoFuncionario());
                }
                
                BancoDeDados.setTabelaFuncionario(tFuncionario);
            }
            
            // Cliente
            
            if(tabelaC != null){
                ArrayList<ClienteModel> tCliente = new ArrayList<ClienteModel>();
                
                for (Object o : tabelaC) {
                    ClienteModel c = (ClienteModel) o;
                    
                    tCliente.add(c);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tCliente.size()) > 0){
                    BancoDeDados.setProximoCodigoCliente(tCliente.get(tCliente.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoCliente(BancoDeDados.getProximoCodigoCliente());
                }
                
                BancoDeDados.setTabelaCliente(tCliente);
            }
            
            // Hotel
            
            if(tabelaH != null){
                ArrayList<HotelModel> tHotel = new ArrayList<HotelModel>();
                
                for (Object o : tabelaH) {
                    HotelModel h = (HotelModel) o;
                    
                    tHotel.add(h);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tHotel.size()) > 0){
                    BancoDeDados.setProximoCodigoHotel(tHotel.get(tHotel.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoHotel(BancoDeDados.getProximoCodigoHotel());
                }
                
                BancoDeDados.setHotelTable(tHotel);
            }
            
            // Transporte
            
            if(tabelaT != null){
                ArrayList<TransporteModel> tTransporte = new ArrayList<TransporteModel>();
                
                for (Object o : tabelaT) {
                    TransporteModel t = (TransporteModel) o;
                    
                    tTransporte.add(t);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tTransporte.size()) > 0){
                    BancoDeDados.setProximoCodigoTransporte(tTransporte.get(tTransporte.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoTransporte(BancoDeDados.getProximoCodigoTransporte());
                }
                
                BancoDeDados.setTransporteTable(tTransporte);
            }
            
            // Plano
            
            if(tabelaP != null){
                ArrayList<PlanoModel> tPlano = new ArrayList<PlanoModel>();
                
                for (Object o : tabelaP) {
                    PlanoModel p = (PlanoModel) o;
                    
                    tPlano.add(p);
                }
                
                /* Atualiza o codigo conforme recupera os dados para que nao
                   haja problema na geracao de novos codigos e eles nao se repitam */
                if((tPlano.size()) > 0){
                    BancoDeDados.setProximoCodigoPlano(tPlano.get(tPlano.size()-1).getCodigo() + 1);
                }
                else{
                    BancoDeDados.setProximoCodigoPlano(BancoDeDados.getProximoCodigoPlano());
                }
                
                BancoDeDados.setPlanoTable(tPlano);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteButton;
    private javax.swing.JButton funcionarioButton;
    private javax.swing.JButton hotelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton localButton;
    private javax.swing.JButton planoDeViagemButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton transporteButton;
    // End of variables declaration//GEN-END:variables
}
